module.exports = {
  MESSAGE_CREATED: "MESSAGE_CREATED",
  IS_USER_ONLINE: "IS_USER_ONLINE",
  NEW_CONVERSATION: "NEW_CONVERSATION",
  NOTIFICATION_CREATED_OR_DELETED: "NOTIFICATION_CREATED_OR_DELETED",
};
